apiVersion: v1
kind: Pod
metadata:
  name: pod-2-containers
spec:
  containers:
    - name: nginx1
      image: nginx
      ports:
        - containerPort: 80
    - name: appserver
      image: tomcat:8
      ports:
        - containerPort: 8080
